site_name: Webhook Manager
site_url: https://github.com/versx/WhMgr
site_description: Webhook manager
site_author: versx

repo_url: https://github.com/versx/whmgr/
edit_uri: ""

theme:
    name: readthedocs #mkdocs, bootstrap4, cinder, cosmo, cyborg, flatly, ivory, material, readthedocs, slate, yeti

extends: mkdocs
hljs_style: docco

nav:
    - Home: index.md
    - General:
        - Screenshots: screenshots.md
        - Terminology: terminology.md
        - Updating: updating.md
    - Installation:
        - Prerequisites: install/prerequisites.md
        - Getting Started: install/getting-started.md
    - Configuration:
        - Config: config/config.md
        - Discord: config/discords.md
        - Geofences: config/geofences.md
        - Alarms: config/alarms.md
        - Filters: config/filters.md
        - Embeds: config/embeds.md
        - DTS:
            - Pokemon: config/dts/pokemon.md
            - Raids & Eggs: config/dts/raids.md
            - Quests: config/dts/quests.md
            - Pokestops: config/dts/pokestops.md
            - Gyms: config/dts/gyms.md
            - Weather: config/dts/weather.md
            - Nests: config/dts/nests.md
    - Commands:
        - Subscriptions: commands/subscriptions.md
        - Owner: commands/owner.md
    - Other:
        - Command Line: other/commandline.md
        - PM2: other/pm2.md
#    - About:
#        - Release Notes: about/release-notes.md
#        - Contributing: about/contributing.md

markdown_extensions:
    - toc:
        permalink: 

copyright: Copyright &copy; 2019 <a href="https://github.com/versx">versx</a>, Maintained by <a href="/about/release-notes.md#maintenance-team">versx</a>.

plugins:
    - search

extra_css:
    - css/base.css
    - css/bootstrap-custom.min.css
